dubbo:
  application:
    name: provider-ticket
  registry:
    address: 192.168.0.11:2181
    protocol: zookeeper
  scan:
    base-packages:
     - com.geral.springboot10.ticket.service
logging:
  level:
   com.geral.springboot10.ticket.service: DEBUG